-- How many sellers are there in total?
SELECT 
    COUNT(DISTINCT seller_id)
FROM
    sellers;

-- Which states have the most sellers?
SELECT 
    seller_state, COUNT(DISTINCT seller_id) AS num_sellers
FROM
    sellers
GROUP BY seller_state
ORDER BY num_sellers DESC
LIMIT 10;

-- Which cities have the most sellers?
SELECT 
    seller_city, COUNT(DISTINCT seller_id) AS num_sellers
FROM
    sellers
GROUP BY seller_city
ORDER BY num_sellers DESC
LIMIT 10;

-- How many sellers are there in each state?
SELECT 
    seller_state, COUNT(DISTINCT seller_id) AS num_sellers
FROM
    sellers
GROUP BY seller_state
ORDER BY num_sellers DESC;

-- Which 10 sellers generate the highest total sales?
SELECT 
    seller_id, ROUND(SUM(price), 2) AS total_sales
FROM
    order_items
GROUP BY seller_id
ORDER BY total_sales DESC
LIMIT 10
;

-- Which 10 sellers sell the most items?
SELECT 
    seller_id, COUNT(*) AS items
FROM
    order_items
GROUP BY seller_id
ORDER BY items DESC
LIMIT 10
;

-- Which 10 sellers have the highest average product price?
SELECT 
    seller_id, ROUND(AVG(price), 2) AS avg_sales
FROM
    order_items
GROUP BY seller_id
ORDER BY avg_sales DESC
LIMIT 10
;

-- Which 10 sellers have the highest total freight cost?
SELECT 
    seller_id,
    ROUND(SUM(freight_value), 2) AS total_freight_value
FROM
    order_items
GROUP BY seller_id
ORDER BY total_freight_value DESC
LIMIT 10
;

-- Which 10 sellers have the highest average freight cost?
SELECT 
    seller_id, ROUND(AVG(freight_value), 2) AS avg_freight_value
FROM
    order_items
GROUP BY seller_id
ORDER BY avg_freight_value DESC
LIMIT 10
;

-- Which 10 sellers have the highest number of orders?
SELECT 
    seller_id, COUNT(DISTINCT order_id) AS num_orders
FROM
    order_items
GROUP BY seller_id
ORDER BY num_orders DESC
LIMIT 10
;

-- What is the average number of items sold per seller?
SELECT 
    ROUND(COUNT(*) / COUNT(DISTINCT seller_id), 2) AS num_orders
FROM
    order_items
;

-- Which sellers have the highest average review score?
SELECT 
    seller_id,
    COUNT(DISTINCT review_id) AS num_reviews,
    ROUND(AVG(review_score), 2) AS avg_review_score
FROM
    order_items oi
        JOIN
    order_reviews orw ON oi.order_id = orw.order_id
GROUP BY seller_id
HAVING COUNT(DISTINCT review_id) >= 10
ORDER BY avg_review_score DESC;

-- Which states generate the highest seller sales?
SELECT 
    seller_state, ROUND(SUM(price), 2) AS total_value
FROM
    sellers s
        JOIN
    order_items oi ON s.seller_id = oi.seller_id
GROUP BY seller_state
ORDER BY total_value DESC;

-- Which sellers have both high sales and high review scores?
SELECT 
    seller_id,
    ROUND(AVG(review_score), 2) AS avg_review_score,
    ROUND(SUM(price), 2) AS sales
FROM
    order_items oi
        JOIN
    order_reviews orw ON oi.order_id = orw.order_id
GROUP BY seller_id
HAVING COUNT(DISTINCT review_id) >= 10
    AND AVG(review_score) >= 4
ORDER BY avg_review_score DESC , sales DESC;

-- What percentage of total sales is generated by the top 10 sellers?
with total_sale as (
	select s.seller_id,round(sum(price),2) as sales
	from sellers s 
	join order_items oi on s.seller_id = oi.seller_id
	group by seller_id
	order by sales desc
	limit 10
	)
select round(sum(sales)/(select sum(price) from order_items)* 100,4) as percentage
from total_sale;
